# Generated by Django 6.0.5 on 2026-06-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.TextField()),
            ],
        ),
    ]
