# Generated by Django 6.0.5 on 2026-06-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag1', '0005_task_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
