# Generated by Django 6.0.5 on 2026-09-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag1', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Medium', max_length=10),
        ),
    ]
