# Generated by Django 6.0.5 on 2026-06-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag1', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
